import ChatRoomList from '../../components/ui/ChatRoomList';
import type { Metadata } from 'next';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { AppSidebar } from '@/components/app-sidebar';
import {
  SidebarInset,
  SidebarProvider,
} from '@/components/ui/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ChatroomLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        {/* Main Layout */}
        <div className="flex h-full bg-gray-950 text-gray-300">
          {/* Left Sidebar (ChatRoomList) */}
          <div className="w-1/4 bg-gray-800 p-4 overflow-y-auto">
            <ChatRoomList />
          </div>

          {/* Right Content (Main Chatroom) */}
          <main className="flex-1 bg-gray-900 p-4 overflow-y-auto">
            {children}
          </main>
        </div>

        <ToastContainer />
      </SidebarInset>
    </SidebarProvider>
  );
}
